// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PatchPetsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Updated
	PatchPets200ApplicationJSONAnyOf interface{}
}

func (o *PatchPetsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PatchPetsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PatchPetsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PatchPetsResponse) GetPatchPets200ApplicationJSONAnyOf() interface{} {
	if o == nil {
		return nil
	}
	return o.PatchPets200ApplicationJSONAnyOf
}
