// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PetByAge struct {
	Age      int64   `json:"age"`
	Nickname *string `json:"nickname,omitempty"`
}

func (o *PetByAge) GetAge() int64 {
	if o == nil {
		return 0
	}
	return o.Age
}

func (o *PetByAge) GetNickname() *string {
	if o == nil {
		return nil
	}
	return o.Nickname
}
