// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type PetType string

const (
	PetTypeCat PetType = "Cat"
	PetTypeDog PetType = "Dog"
)

func (e PetType) ToPointer() *PetType {
	return &e
}

func (e *PetType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Cat":
		fallthrough
	case "Dog":
		*e = PetType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PetType: %v", v)
	}
}

type PetByType struct {
	Hunts   *bool   `json:"hunts,omitempty"`
	PetType PetType `json:"pet_type"`
}

func (o *PetByType) GetHunts() *bool {
	if o == nil {
		return nil
	}
	return o.Hunts
}

func (o *PetByType) GetPetType() PetType {
	if o == nil {
		return PetType("")
	}
	return o.PetType
}
